### ISSUE TITLE
Is this one supposed to fail?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/scs-akka#8]
http://localhost:9000/objects/find/valueequals?propertyurn=urn:cite2:hmt:msA.v1.image:&value=urn:cite2:hmt:vaimg.v1:VA013RN_0014

**Comment by Eumaeus** [comment]
Burned again by our damned inconsistant (once upon a time) version IDs.

This works: <http://localhost:9000/objects/find/valueequals?propertyurn=urn:cite2:hmt:msA.v1.image:&value=urn:cite2:hmt:vaimg.2017a:VA013RN_0014>

Updated.
